export const GET_USERS = 'GET_USERS';

export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAILED = 'GET_SESSION_FAILED';
export const GET_SESSION_REQUESTED = 'GET_SESSION_REQUESTED';
